version: '3.1'
services:
  web:
    image: odoo:17
    container_name: baseConfig
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:latest
    container_name: baseConfig_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
